#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading thermal bits into the initramfs

. /usr/share/initramfs-tools/hook-functions

case "$DPKG_ARCH" in
# copy the right modules
powerpc|ppc64)
	if [ -e /sys/bus/ps3_system_bus/ ]; then
		exit 0
	fi
	force_load therm_pm72
	force_load windfarm_core
	force_load windfarm_cpufreq_clamp
	force_load windfarm_lm75_sensor
	force_load windfarm_max6690_sensor
	force_load windfarm_pid
	force_load windfarm_pm112
	force_load windfarm_pm81
	force_load windfarm_pm91
	force_load windfarm_smu_controls
	force_load windfarm_smu_sat
	force_load windfarm_smu_sensors
	force_load i2c-powermac
	;;
i386|amd64|ia64)
	manual_add_modules fan
	manual_add_modules thermal
	;;
esac
